name: Cloudflare Worker Pipeline
on:
  push:
    branches: [main]
    paths:
      - "cloudflare/**"

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./cloudflare

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js Latest
        uses: actions/setup-node@v4
        with:
          node-version: "node"

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Install Dependencies
        run: pnpm install

      - name: Verify WSL Script URL
        run: |
          URL="https://raw.githubusercontent.com/jfalava/outfitting/refs/heads/main/wsl-install-script.sh"
          if ! curl -L --fail -I -o /dev/null -s "$URL"; then
            echo "::error::WSL script URL unreachable: $URL"
            exit 1
          fi
          echo "Successfully verified $URL"

      - name: Verify Windows Script URL
        run: |
          URL="https://raw.githubusercontent.com/jfalava/outfitting/refs/heads/main/windows-install-script.ps1"
          if ! curl -L --fail -I -o /dev/null -s "$URL"; then
            echo "::error::Windows script URL unreachable: $URL"
            exit 1
          fi
          echo "Successfully verified $URL"

      - name: Deploy to Cloudflare
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: pnpm run deploy
